server:
  port: 8091
  forward-headers-strategy: framework
spring:
  application:
    name: MedHeadProject-2
  datasource:
    url: jdbc:h2:mem:MedHead;
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    database: h2
  sql:
    init:
      #schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      mode: always
  h2:
    console:
      enabled: true
      path: /h2
  data:
    jpa:
      repositories:
        bootstrap-mode: default
springdoc:
  swagger-ui:
    path: /swagger-ui
